/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_CLOCKDATA_H
#define YARP_THRIFT_GENERATOR_STRUCT_CLOCKDATA_H

#include <yarp/dev/api.h>

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp::dev {

class YARP_dev_API ClockData :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    std::int32_t sec{0};
    std::int32_t nsec{0};

    // Default constructor
    ClockData() = default;

    // Constructor with field values
    ClockData(const std::int32_t sec,
              const std::int32_t nsec);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<ClockData> unwrapped;

    class Editor :
            public yarp::os::Wire,
            public yarp::os::PortWriter
    {
    public:
        // Editor: default constructor
        Editor();

        // Editor: constructor with base class
        Editor(ClockData& obj);

        // Editor: destructor
        ~Editor() override;

        // Editor: Deleted constructors and operator=
        Editor(const Editor& rhs) = delete;
        Editor(Editor&& rhs) = delete;
        Editor& operator=(const Editor& rhs) = delete;
        Editor& operator=(Editor&& rhs) = delete;

        // Editor: edit
        bool edit(ClockData& obj, bool dirty = true);

        // Editor: validity check
        bool isValid() const;

        // Editor: state
        ClockData& state();

        // Editor: start editing
        void start_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use start_editing() instead")
        void begin()
        {
            start_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: stop editing
        void stop_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use stop_editing() instead")
        void end()
        {
            stop_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: sec field
        void set_sec(const std::int32_t sec);
        std::int32_t get_sec() const;
        virtual bool will_set_sec();
        virtual bool did_set_sec();

        // Editor: nsec field
        void set_nsec(const std::int32_t nsec);
        std::int32_t get_nsec() const;
        virtual bool will_set_nsec();
        virtual bool did_set_nsec();

        // Editor: clean
        void clean();

        // Editor: read
        bool read(yarp::os::ConnectionReader& connection) override;

        // Editor: write
        bool write(yarp::os::ConnectionWriter& connection) const override;

    private:
        // Editor: state
        ClockData* obj;
        bool obj_owned;
        int group;

        // Editor: dirty variables
        bool is_dirty;
        bool is_dirty_sec;
        bool is_dirty_nsec;
        int dirty_count;

        // Editor: send if possible
        void communicate();

        // Editor: mark dirty overall
        void mark_dirty();

        // Editor: mark dirty single fields
        void mark_dirty_sec();
        void mark_dirty_nsec();

        // Editor: dirty_flags
        void dirty_flags(bool flag);
    };

private:
    // read/write sec field
    bool read_sec(yarp::os::idl::WireReader& reader);
    bool write_sec(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_sec(yarp::os::idl::WireReader& reader);
    bool nested_write_sec(const yarp::os::idl::WireWriter& writer) const;

    // read/write nsec field
    bool read_nsec(yarp::os::idl::WireReader& reader);
    bool write_nsec(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_nsec(yarp::os::idl::WireReader& reader);
    bool nested_write_nsec(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::dev

#endif // YARP_THRIFT_GENERATOR_STRUCT_CLOCKDATA_H
