/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_CLOCKDATA_H
#define YARP_THRIFT_GENERATOR_STRUCT_CLOCKDATA_H

#include <yarp/dev/api.h>

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp::dev {

class YARP_dev_API ClockData :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    std::int32_t sec{0};
    std::int32_t nsec{0};

    // Default constructor
    ClockData() = default;

    // Constructor with field values
    ClockData(const std::int32_t sec,
              const std::int32_t nsec);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<ClockData> unwrapped;

private:
    // read/write sec field
    bool read_sec(yarp::os::idl::WireReader& reader);
    bool write_sec(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_sec(yarp::os::idl::WireReader& reader);
    bool nested_write_sec(const yarp::os::idl::WireWriter& writer) const;

    // read/write nsec field
    bool read_nsec(yarp::os::idl::WireReader& reader);
    bool write_nsec(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_nsec(yarp::os::idl::WireReader& reader);
    bool nested_write_nsec(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::dev

#endif // YARP_THRIFT_GENERATOR_STRUCT_CLOCKDATA_H
