/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_RETURN_BACKUPBOT_H
#define YARP_THRIFT_GENERATOR_STRUCT_RETURN_BACKUPBOT_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace yarp::dev::chatbot {

class return_backupBot :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    bool result{false};
    std::string backupString{};

    // Default constructor
    return_backupBot() = default;

    // Constructor with field values
    return_backupBot(const bool result,
                     const std::string& backupString);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<return_backupBot> unwrapped;

private:
    // read/write result field
    bool read_result(yarp::os::idl::WireReader& reader);
    bool write_result(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_result(yarp::os::idl::WireReader& reader);
    bool nested_write_result(const yarp::os::idl::WireWriter& writer) const;

    // read/write backupString field
    bool read_backupString(yarp::os::idl::WireReader& reader);
    bool write_backupString(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_backupString(yarp::os::idl::WireReader& reader);
    bool nested_write_backupString(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::dev::chatbot

#endif // YARP_THRIFT_GENERATOR_STRUCT_RETURN_BACKUPBOT_H
